/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eduPort;
import java.util.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manish pandey
 */

public class DeleteUI extends javax.swing.JFrame {

    /**
     * Creates new form Delete_ui
     */
    private EduPortMngr mngr;
//    private DocumentMngr dm;
    public DeleteUI(EduPortMngr mngr) {
        this.mngr=mngr;
        initComponents();
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setFont(new Font("Comic Sans MS",Font.BOLD,14));
        jTable2.getTableHeader().setBackground(new Color(0,0,0));
        populateData(mngr.getDocumentMngr().getDocTODel(mngr.getCurrUser()));

        
    }
    
     public void setColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(241,95,121));
 }
 
 public void resetColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(51,51,51));
 }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kButton8 = new keeptoo.KButton();
        kButton9 = new keeptoo.KButton();
        kButton10 = new keeptoo.KButton();
        kButton11 = new keeptoo.KButton();
        kButton12 = new keeptoo.KButton();
        kButton13 = new keeptoo.KButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Vector (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 60, 160, 120));

        jScrollPane3.setBackground(new Color(0,0,0,0));
        jScrollPane3.setBorder(null);
        jScrollPane3.setOpaque(false);

        jScrollPane2.setBackground(new Color(0,0,0,0));
        jScrollPane2.setOpaque(false);

        jTable2.setBackground(new Color(0,0,0,0));
        jTable2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "a", "b"},
                {"2", "a", "b"},
                {"3", "a", "b"},
                {"4", "a", "b"}
            },
            new String [] {
                "S.No.", "Book Name", "Author Name"
            }
        ));
        jTable2.setFocusable(false);
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setOpaque(false);
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(241, 95, 121));
        jTable2.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("S.No.");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Book Name");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Author Name");
        }

        jScrollPane3.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 300, 800, 190));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("           Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 166, -1));

        kButton1.setText("Delete");
        kButton1.setkBorderRadius(40);
        kButton1.setkEndColor(new java.awt.Color(241, 95, 121));
        kButton1.setkStartColor(new java.awt.Color(200, 78, 131));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Upload details");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 220, -1));

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\feedback (2).png")); // NOI18N
        kButton8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton8.setIconTextGap(35);
        kButton8.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton8.setkBorderRadius(0);
        kButton8.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton8.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton8.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton8.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 120, 100));

        kButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton9.setIconTextGap(35);
        kButton9.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton9.setkBorderRadius(0);
        kButton9.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton9.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton9.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton9.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton9.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 100));

        kButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        kButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton10.setIconTextGap(35);
        kButton10.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton10.setkBorderRadius(0);
        kButton10.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton10.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton10.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton10.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, 100));

        kButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        kButton11.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton11.setIconTextGap(35);
        kButton11.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton11.setkBorderRadius(0);
        kButton11.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton11.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton11.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton11.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton11.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, 100));

        kButton12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\upload_active.png")); // NOI18N
        kButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton12.setIconTextGap(35);
        kButton12.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton12.setkBorderRadius(0);
        kButton12.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton12.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton12.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton12.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, 100));

        kButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/request book.png"))); // NOI18N
        kButton13.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton13.setIconTextGap(35);
        kButton13.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton13.setkBorderRadius(0);
        kButton13.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton13.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton13.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton13.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton13.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton13.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton13.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 30, 30));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 30, 30));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void populateData(ArrayList<Document> doclist)
     {

          jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {"1",doclist.get(0).getTitle() ,doclist.get(0).getAuthorName() },
                {"2",doclist.get(1).getTitle() ,doclist.get(1).getAuthorName() },
                {"3",doclist.get(2).getTitle() ,doclist.get(2).getAuthorName() },
                {"4",doclist.get(3).getTitle() ,doclist.get(3).getAuthorName() },
                {"5",doclist.get(4).getTitle() ,doclist.get(4).getAuthorName() },
                {"6",doclist.get(5).getTitle() ,doclist.get(5).getAuthorName() },
                {"7",doclist.get(6).getTitle() ,doclist.get(6).getAuthorName() },
                // {"1",doclist.get(0).getTitle() ,doclist.get(0).getAuthorName() },     
            },
            new String [] {
                "S.No.", "Book Name", "Author Name"
            }
        ));
     }       
    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
         int SelectedRow = jTable2.getSelectedRow(); 
         String title=(jTable2.getValueAt(SelectedRow,1)).toString();
         String authorName=jTable2.getValueAt(SelectedRow,2).toString();
         boolean b=mngr.getDocumentMngr().deleteDocument(title, authorName);
        if(SelectedRow>=0){
        int p= JOptionPane.showConfirmDialog(null, "Do you want to really delete the selected book?","Delete", JOptionPane.YES_NO_OPTION);
        if(p==0&&b){
       
           model.removeRow(SelectedRow);
           
          JOptionPane.showMessageDialog(null,"Book deleted Successfully!");
        }
        else if(p==0)
        {
            JOptionPane.showMessageDialog(null,"serverError!! couldn't be deleted now ");
        }
        }
        else{
        JOptionPane.showMessageDialog(rootPane, "Please Select a book to delete");
        }
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        setColor(jLabel5);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        resetColor(jLabel5);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        setColor(jLabel6);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        resetColor(jLabel6);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        if(this.getExtendedState()!=JFrame.MAXIMIZED_BOTH){
           this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
        else{
        this.setExtendedState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        setColor(jLabel4);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
        resetColor(jLabel4);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
         this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel4MousePressed
      int xx,xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy); 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
        mngr.feedbackScreen();
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        // TODO add your handling code here:
        if(mngr.getCurrUser().equals("")){
            mngr.signUpScreen();
        }else{
            //show user uploaded files
        }
    }//GEN-LAST:event_kButton10ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        mngr.searchScreen();
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton12ActionPerformed

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
        mngr.requestScreen();
    }//GEN-LAST:event_kButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DeleteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DeleteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DeleteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DeleteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DeleteUI(DocumentMngr.getObject()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private keeptoo.KButton kButton8;
    private keeptoo.KButton kButton9;
    // End of variables declaration//GEN-END:variables
}
