/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package eduPort;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author manish pandey
 */
public class Download_viewUI extends javax.swing.JFrame {

    /**
     * Creates new form download_viewui
     */
    private EduPortMngr mngr;
    public Download_viewUI(EduPortMngr mngr) {
        this.mngr=mngr;
        initComponents();
        jTextArea1.setOpaque(false);
        //jTextArea1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
//        scaleImage();
    }
    
    public void setColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(241,95,121));
 }
 
 public void resetColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(51,51,51));
 }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        kButton8 = new keeptoo.KButton();
        kButton9 = new keeptoo.KButton();
        kButton10 = new keeptoo.KButton();
        kButton11 = new keeptoo.KButton();
        kButton12 = new keeptoo.KButton();
        kButton13 = new keeptoo.KButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\book_bg_img.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 290, 230));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new Color(0,0,0,0));
        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 255));
        jTextField1.setText("Book Name  ");
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 150, 44));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new Color(0,0,0,0));
        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Pal AND Das pt1");
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 181, -1));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Engineering mathematics");
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(51, 51, 51));
        jTextArea1.setOpaque(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(255, 0, 255));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 306, -1));

        jLabel3.setBackground(new Color(0,0,0,0));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Author Name:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        jLabel4.setBackground(new Color(0,0,0,0));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Book Description:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        kButton1.setText("Download");
        kButton1.setFont(new java.awt.Font("Corbel", 1, 16)); // NOI18N
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new java.awt.Color(241, 95, 121));
        kButton1.setkHoverEndColor(new java.awt.Color(241, 95, 121));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(200, 78, 137));
        kButton1.setkStartColor(new java.awt.Color(200, 78, 131));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\feedback (2).png")); // NOI18N
        kButton8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton8.setIconTextGap(35);
        kButton8.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton8.setkBorderRadius(0);
        kButton8.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton8.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton8.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton8.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 120, 100));

        kButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton9.setIconTextGap(35);
        kButton9.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton9.setkBorderRadius(0);
        kButton9.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton9.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton9.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton9.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton9.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 100));

        kButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        kButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton10.setIconTextGap(35);
        kButton10.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton10.setkBorderRadius(0);
        kButton10.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton10.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton10.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton10.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, 100));

        kButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        kButton11.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton11.setIconTextGap(35);
        kButton11.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton11.setkBorderRadius(0);
        kButton11.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton11.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton11.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton11.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton11.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, 100));

        kButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Upload.png"))); // NOI18N
        kButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton12.setIconTextGap(35);
        kButton12.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton12.setkBorderRadius(0);
        kButton12.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton12.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton12.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton12.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, 100));

        kButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/request book.png"))); // NOI18N
        kButton13.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton13.setIconTextGap(35);
        kButton13.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton13.setkBorderRadius(0);
        kButton13.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton13.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton13.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton13.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton13.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton13.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton13.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 702));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new Color(0,0,0,0));
        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Das and pal");
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 181, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\bg2.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 150, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\bg2.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 340, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xx,xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy); 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        String title=jTextField2.getText();
        String authorName=jTextField3.getText();
        String path=mngr.getDocumentMngr().downloadDocument(title, authorName);
        File f =new File(path);
        boolean t =f.exists();
        if(t){     
            JFileChooser jf = new JFileChooser();
        jf.setDialogTitle("Choose a directory to save your file: ");
        jf.showSaveDialog(this);
        File ff = jf.getSelectedFile();
        String p1=f.getAbsolutePath() ;
       String p2=ff.getAbsolutePath() ;
        Path source = Paths.get(p1);
    Path destination = Paths.get(p2);
 
            try {
                Files.copy(source, destination, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(Download_viewUI.class.getName()).log(Level.SEVERE, null, ex);
            }
//boolean g = f.renameTo(new File(ff.getAbsolutePath()));
        if (ff.exists()) {
            JOptionPane.showMessageDialog(rootPane,"File downloaded Successfully!");
            if(Desktop.isDesktopSupported()){
                try {
                    Desktop.getDesktop().open(ff);
                } catch (IOException ex) {
                    Logger.getLogger(Download_viewUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            }
            else{
            JOptionPane.showMessageDialog(rootPane,"File not Supported!");
            }
        }
        
        else{
        JOptionPane.showMessageDialog(rootPane,"Download Failed! Please try again");
        }
        }
        else{
        JOptionPane.showMessageDialog(rootPane,"File to be uploaded Soon!");
        }
        
    }//GEN-LAST:event_kButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
        mngr.feedbackScreen();
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        // TODO add your handling code here:
        if(mngr.getCurrUser().equals("")){
            mngr.signUpScreen();
        }else{
            //show user uploaded files
        }
    }//GEN-LAST:event_kButton10ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        mngr.searchScreen();
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
        mngr.uploadScreen();
    }//GEN-LAST:event_kButton12ActionPerformed

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private keeptoo.KButton kButton8;
    private keeptoo.KButton kButton9;
    // End of variables declaration//GEN-END:variables
}
