/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eduPort;

import java.awt.Image;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author manis
 */
public class FeedbackUi extends javax.swing.JFrame {

    
    
    private EduPortMngr mngr;
    /**
     * Creates new form Feedbackui2
     * 
     */
    public FeedbackUi(EduPortMngr mgr) {
        this.mngr = mgr;
        initComponents();
        // Color c = new Color(52,52,52,1);
       // getContentPane().setBackground(Color.white);
//        scaleImage();
    }
    
//    private void scaleImage() {
//        ImageIcon icon = new ImageIcon("C:\\Users\\manis\\Documents\\NetBeansProjects\\feedbackui1\\src\\image\\feedback_1.png");
//        Image img = icon.getImage();
//        Image imgScale = img.getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ScaledIcon =new ImageIcon(imgScale);
//        jLabel2.setIcon(ScaledIcon);
//        
//         ImageIcon icon3 = new ImageIcon("C:\\Users\\manis\\Documents\\NetBeansProjects\\feedbackui1\\src\\image\\icons8_delete_50px_4.png");
//        Image img3 = icon3.getImage();
//        Image imgScale3 = img3.getScaledInstance(jLabel8.getWidth(), jLabel8.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ScaledIcon3 =new ImageIcon(imgScale3);
//        jLabel8.setIcon(ScaledIcon3);
//     
//    
////        
//        ImageIcon icon1 = new ImageIcon("C:\\Users\\manis\\Documents\\NetBeansProjects\\feedbackui1\\src\\image\\icons8_maximize_window_50px_1.png");
//        Image img1 = icon1.getImage();
//        Image imgScale1 = img1.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ScaledIcon1 =new ImageIcon(imgScale1);
//        jLabel10.setIcon(ScaledIcon1);
//        
//        ImageIcon icon2 = new ImageIcon("C:\\Users\\manis\\Documents\\NetBeansProjects\\feedbackui1\\src\\image\\icons8_minimize_window_50px.png");
//        Image img2 = icon2.getImage();
//        Image imgScale2 = img2.getScaledInstance(jLabel14.getWidth(), jLabel14.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon ScaledIcon2 =new ImageIcon(imgScale2);
//        jLabel14.setIcon(ScaledIcon2);
//    }
    
     public void setColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(241,95,121));
 }
 
 public void resetColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(51,51,51));
 }
//    class jPanelGradient extends JPanel{
//        
//        protected void paintComponent(Graphics g){
//        
//           Graphics2D g2d = (Graphics2D) g;
//           int width = getWidth();
//           int height = getHeight();
//    
//           Color color1 = new Color(52,143,80);
//           Color color2 = new Color(86,180,211);
//    
//           GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
//           g2d.setPaint(gp);
//           g2d.fillRect(0, 0, width, height);
//    
//    }
//    }
//    class jPanelGradient1 extends JButton{
//        
//        protected void paintComponent(Graphics g){
//        
//           Graphics2D g2d = (Graphics2D) g;
//           int width = getWidth();
//           int height = getHeight();
//    
//           Color color1 = new Color(52,143,80);
//           Color color2 = new Color(86,180,211);
//    
//           GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
//           g2d.setPaint(gp);
//           g2d.fillRect(0, 0, width, height);
//    
//    }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        kButton1 = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        kButton8 = new keeptoo.KButton();
        kButton9 = new keeptoo.KButton();
        kButton10 = new keeptoo.KButton();
        kButton11 = new keeptoo.KButton();
        kButton12 = new keeptoo.KButton();
        kButton13 = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sengar\\Desktop\\OOPs Lab\\intrgratr\\devMate\\src\\image\\feedback_1.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 347, 290));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Where did you first hear about us?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("How was your experience?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Will you recommemd this platform to your friends?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kindly give your suggestions for future updates");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, -1, -1));

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Freind");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Social Site");
        jCheckBox2.setOpaque(false);
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        buttonGroup1.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("Other");
        jCheckBox3.setOpaque(false);
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        buttonGroup2.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Could be better");
        jCheckBox4.setOpaque(false);
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        buttonGroup2.add(jCheckBox5);
        jCheckBox5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Good");
        jCheckBox5.setOpaque(false);
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        buttonGroup2.add(jCheckBox6);
        jCheckBox6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setText("Best");
        jCheckBox6.setOpaque(false);
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, -1, -1));

        buttonGroup3.add(jCheckBox7);
        jCheckBox7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setText("Yes");
        jCheckBox7.setOpaque(false);
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        buttonGroup3.add(jCheckBox8);
        jCheckBox8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setText("No");
        jCheckBox8.setOpaque(false);
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        buttonGroup3.add(jCheckBox9);
        jCheckBox9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setText("Maybe");
        jCheckBox9.setOpaque(false);
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 430, 376, -1));

        kButton1.setText("Submit");
        kButton1.setBorderPainted(false);
        kButton1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        kButton1.setkBorderRadius(0);
        kButton1.setkEndColor(new java.awt.Color(241, 95, 121));
        kButton1.setkStartColor(new java.awt.Color(200, 78, 137));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 135, -1));

        jPanel2.setBackground(new java.awt.Color(38, 38, 38));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/feedback (2)_active.png"))); // NOI18N
        kButton8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton8.setIconTextGap(35);
        kButton8.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton8.setkBorderRadius(0);
        kButton8.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton8.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton8.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton8.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton8.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 120, 100));

        kButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton9.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton9.setIconTextGap(35);
        kButton9.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton9.setkBorderRadius(0);
        kButton9.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton9.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton9.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton9.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton9.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton9.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton9.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 120, 100));

        kButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        kButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton10.setIconTextGap(35);
        kButton10.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton10.setkBorderRadius(0);
        kButton10.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton10.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton10.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton10.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton10.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton10.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, 100));

        kButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        kButton11.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton11.setIconTextGap(35);
        kButton11.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton11.setkBorderRadius(0);
        kButton11.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton11.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton11.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton11.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton11.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton11.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton11.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, 100));

        kButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Upload.png"))); // NOI18N
        kButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton12.setIconTextGap(35);
        kButton12.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton12.setkBorderRadius(0);
        kButton12.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton12.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton12.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton12.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton12.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton12.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 120, 100));

        kButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/request book.png"))); // NOI18N
        kButton13.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        kButton13.setIconTextGap(35);
        kButton13.setkBackGroundColor(new java.awt.Color(38, 38, 38));
        kButton13.setkBorderRadius(0);
        kButton13.setkEndColor(new java.awt.Color(38, 38, 38));
        kButton13.setkForeGround(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverColor(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverEndColor(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverForeGround(new java.awt.Color(38, 38, 38));
        kButton13.setkHoverStartColor(new java.awt.Color(38, 38, 38));
        kButton13.setkIndicatorColor(new java.awt.Color(38, 38, 38));
        kButton13.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton13.setkSelectedColor(new java.awt.Color(51, 51, 51));
        kButton13.setkStartColor(new java.awt.Color(38, 38, 38));
        kButton13.setPreferredSize(new java.awt.Dimension(100, 60));
        kButton13.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        kButton13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(kButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 120, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 708));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 90, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        
        String p = null,q = null,r = null;
        //get the text of the checkbox selected
        Enumeration<AbstractButton> bg1 = buttonGroup1.getElements();
        while(bg1.hasMoreElements()){
        JCheckBox jcb1 = (JCheckBox) bg1.nextElement();
        if(jcb1.isSelected()){
           p = jcb1.getText();
           //jcb1.setSelected(false);
        }
        }
        
        Enumeration<AbstractButton> bg2 = buttonGroup2.getElements();
        while(bg2.hasMoreElements()){
        JCheckBox jcb2 = (JCheckBox) bg2.nextElement();
        if(jcb2.isSelected()){
           q = jcb2.getText();
           //jcb2.setSelected(false);
        }
        }
        
        Enumeration<AbstractButton> bg3 = buttonGroup3.getElements();
        while(bg3.hasMoreElements()){
        JCheckBox jcb3 = (JCheckBox) bg3.nextElement();
        if(jcb3.isSelected()){
          r =  jcb3.getText();
          //jcb3.setSelected(false);
        }
        }
        
        //get the input
        
        mngr.addFeedback(new Feedback(p,q,r,jTextArea1.getText()));
        
        //reset the the fields
        jTextArea1.setText("   ");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        
//        Enumeration<AbstractButton> bg4 = buttonGroup1.getElements();
//        while(bg4.hasMoreElements()){
//        JCheckBox jcb4 = (JCheckBox) bg4.nextElement();
//        if(jcb4.isSelected()){
//          jcb4.setSelected(false);
//        }
//        }
//        
//        Enumeration<AbstractButton> bg5 = buttonGroup2.getElements();
//        while(bg5.hasMoreElements()){
//        JCheckBox jcb5 = (JCheckBox) bg5.nextElement();
//        if(jcb5.isSelected()){
//          jcb5.setSelected(false);
//        }
//        }
//        
//        Enumeration<AbstractButton> bg6 = buttonGroup3.getElements();
//        while(bg6.hasMoreElements()){
//        JCheckBox jcb6 = (JCheckBox) bg6.nextElement();
//        if(jcb6.isSelected()){
//          jcb6.setSelected(false);
//        }
//        }
//        jCheckBox1.setSelected(false);
//        jCheckBox2.setSelected(false);
//        jCheckBox3.setSelected(false);
//        jCheckBox4.setSelected(false);
//        jCheckBox5.setSelected(false);
//        jCheckBox6.setSelected(false);
//        jCheckBox7.setSelected(false);
//        jCheckBox8.setSelected(false);
//        jCheckBox9.setSelected(false);
       
    }//GEN-LAST:event_kButton1ActionPerformed
    int xx,xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy); 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void kButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton8ActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        // TODO add your handling code here:
        if(mngr.getCurrUser().equals("")){
            mngr.signUpScreen();
        }else{
            //show user uploaded files
        }
    }//GEN-LAST:event_kButton10ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        mngr.searchScreen();
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton12ActionPerformed

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FeedbackUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FeedbackUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FeedbackUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FeedbackUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FeedbackUi(new FeedbackManager()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private keeptoo.KButton kButton8;
    private keeptoo.KButton kButton9;
    // End of variables declaration//GEN-END:variables
}
